apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-redis

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-redis
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - nonroot
    resources:
      - securitycontextconstraints
    verbs:
      - use

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-redis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-redis
subjects:
  - kind: ServiceAccount
    name: argocd-redis
