apiVersion: v1
kind: Pod
metadata:
  name: nginx
  # namespace: test-paolo
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    run: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources: {}
    ports:
    - containerPort: 80
    volumeMounts:
      - name: config
        mountPath: /etc/nginx/conf.d
  volumes:
    - name: config
      configMap:
        name: nginx

