apiVersion: v1
kind: Pod
metadata:
  name: kubeo
  namespace: namespace00
  labels:
    run: kubeo
spec:
  containers:
    - name:  nginx
      image: nginx:latest
      resources: {}
      volumeMounts:
        - name: content-data
          mountPath: /usr/share/nginx/html
  volumes:
    - name: content-data
      persistentVolumeClaim:
        claimName: pvc
