kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc
  # namespace: namespace00
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi