kind: ResourceQuota
apiVersion: v1
metadata:
  name: pods-quota-namespace
  namespace: namespace00
spec:
  hard:
    pods: '5'
    # requests.cpu: 5
    # requests.memory: 5Gi
    # requests.storage: 50Gi

