apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - rbac.yaml

commonLabels:
  component: repo-server
  # required by argocd
  app.kubernetes.io/name: argocd-repo-server
  app.kubernetes.io/component: repo-server
