
########################################
# This Secret must be the same as ../../50_argo-workflows/2_argo-server/secret.yaml/argo-workflows-sso
########################################

apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-sso
type: Opaque
stringData:
  client-id: argo-workflows-sso
  client-secret: GV2zMEy3Ug8RUUpkstwypMBMLVQqQ4Qp
