apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace:
  labels:
    run: nginx
spec:
  containers:
  - name: container-1
    image: bsctl/nginx:latest
    ports:
    - containerPort: 80
    securityContext:
      runAsUser: 405
