apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd-gpg-keys-cm.yaml
  - argocd-ssh-known-hosts-cm.yaml
  - argocd-tls-certs-cm.yaml
  # custom
  - argocd-cm.yaml
  - argocd-rbac-cm.yaml

commonLabels:
  group: configs
