# Example of using an InitContainer in place of a GitRepo volume.
# Unilke GitRepo volumes, this approach runs the git command in an init container.
apiVersion: v1
kind: Pod
metadata:
  name: jellyfish
  namespace:
  labels:
    run: jellyfish
spec:
  initContainers:
    - name: git-clone
      image: alpine/git
      args: ["clone", "--", "https://github.com/bsctl/jellyfish.git", "/repo"]
      volumeMounts:
        - name: content-data
          mountPath: /repo
  containers:
    - name:  nginx
      image: nginx:latest
      volumeMounts:
        - name: content-data
          mountPath: /usr/share/nginx/html
  volumes:
    - name: content-data
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfish
  labels:
spec:
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80
  selector:
    run: jellyfish
  type: LoadBalancer