apiVersion: v1
kind: Pod
metadata:
  name: pre-stop-hook
spec:
  containers:
  - image: k8spatterns/random-generator:1.0
    name: random-generator
    resources: {}
    lifecycle:
      preStop:
        httpGet:
          port: 8080
          path: /shutdown