apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-dns
  labels:
    monitored-component: kube-dns
spec:
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app: prometheus
      domain: monitoring
      feature: prometheus
      component: kube-dns
  endpoints:
    - port: kubedns-metrics
      interval: 30s
      scrapeTimeout: 29s
      honorLabels: true
    - port: sidecar-metrics
      interval: 30s
      scrapeTimeout: 29s
      honorLabels: true
