# Commented out cause of problems. Introduced with ArgoCD 2.0.3
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: argocd-application-controller-network-policy
# spec:
#   ingress:
#     - from:
#         - namespaceSelector: {}
#       ports:
#         - port: 8082
#   podSelector:
#     matchLabels:
#       app.kubernetes.io/name: argocd-application-controller
#   policyTypes:
#     - Ingress
