apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-application-controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-application-controller
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - appprojects
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-application-controller
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-application-controller
rules:
  - apiGroups:
      - ""
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups: 
      - apps
      - batch
      - autoscaling
      - argoproj.io
      - networking.k8s.io
      - apiextensions.k8s.io
      - certificates.k8s.io
      - snapshot.storage.k8s.io
      - node.k8s.io
      - migration.k8s.io
      - scheduling.k8s.io
      - apiregistration.k8s.io
      - discovery.k8s.io
      - rbac.authorization.k8s.io
      - admissionregistration.k8s.io
      - storage.k8s.io
      - internal.autoscaling.k8s.io
      - traefik.containo.us
      - monitoring.coreos.com
      - nodemanagement.gke.io
      - networking.gke.io
      - cloud.google.com
      - crd.projectcalico.org
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - "extensions"
    resources:
      - 'ingresses'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - "policy"
    resources:
      - 'poddisruptionbudgets'
    verbs:
      - '*'
  - apiGroups:
      - "policy"
    resources:
      - 'podsecuritypolicies'
    verbs:
      - 'list'
      - 'get'
      - 'delete'
      - 'create'
      - 'patch'
      - 'watch'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-application-controller
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd
